### ISSUE TITLE
1st-camera mode clickable for parked vehicles

### ISSUE THREAD

**Issue by Vectorial1024** [Asu4ni/CitiesSkylines-FPSCamera#15]
For example:

![Screenshot](https://user-images.githubusercontent.com/17726797/158048535-eb780a83-aa1d-4bbc-8fda-fdb38080c18c.png)

Entering 1st person mode for a parked vehicle seems unintended, but I can click on the "enter 1st person mode" button, just that it will have no effect.

**Comment by Asu4ni** [comment]
I noticed this already too :upside_down_face:. The game somehow distinguishes `ParkedVehicle` from `Vehicle`, and `Vehicle` and `Citizen` are the only `InstanceType`s that are accepted to follow at the moment. 

Because it seems quite unnecessary to follow a parked vehicle and I guess that the vehicle would change its ID when transitioning between "parked" and "running", I'd say that we simply don't support it and remove/disable the buttons for `ParkedVehicle`s. Or I'm glad to hear if anyone has better suggestions.

**Comment by Vectorial1024** [comment]
It is understandable. However when I was testing this earlier, I found that when I was already in 1st-person mode, I actually cannot click the buttons on the parked vehicles to enter their 1st person, so perhaps this is an inconsistency that should be solved.

**Comment by Asu4ni** [comment]
That is intentional. The mod would disable those buttons (including `Start Walk-Through`) when it enters any modes, and enable them again after it becomes idle. I do agree that we should remove the button for parked vehicles for clarity.

**Comment by Asu4ni** [comment]
I've looked into this a bit. It seems that `Vehicle` and `ParkedVehicle` share the same `InfoPanel`, so it's tricky to fix this. I supposed that we should probably support following a parked vehicle and handle the transition between these two as well.
