### ISSUE TITLE
This mod is using somthing from the old First Person Camera: Updated mod

### ISSUE THREAD

**Issue by StayHungryStayFoolish2021** [Asu4ni/CitiesSkylines-FPSCamera#40]
## Bug Description
Crash without dialog box after successfully finishing the loading procedure.

## Bug Reproduction
I have unsubscribed from and started to use this mod, but it seems, that this has an issue. The game crashed right after the loading after the successful loading of 10-12 seconds. I tried dozen times, from 10 it crashed 9 times. This is what I have found in output TXT:

Exception while updating CustomBehaviours System.TypeLoadException: Could not load type 'FPSCamera.VehicleCamera' from assembly 'FPSCamera, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. at BehaviourUpdater.Utils.SafelyIterableList`1 [UnityEngine.MonoBehaviour].CallUpdate () [0x00000]

It is repeated million times in OUTPUT.TXT

I asked Krzychu1245 (author of PFS Booster) to check the output TXT and he thinks that this First Person Camera uses the same assembly name which confuses the old mod and tries to access something, which obviously fails as the new FPSCamera code is different than the original one.

## Expected behavior
It should not crash.

## Screenshots
Since the crash is not producing a dialog box, it is not possible to show. Otherwise, my city looks good, I love to work on it and I am building a METRO line fully rendered.

## Log files
[https://drive.google.com/file/d/1LfOzAE5VCIXNFeCpGl8iU-xvuD54-vwq](https://steamcommunity.com/linkfilter/?url=https://drive.google.com/file/d/1LfOzAE5VCIXNFeCpGl8iU-xvuD54-vwq
![HiresScreenshot 126](https://user-images.githubusercontent.com/92725461/166228353-5d2293ea-da96-4c87-90cf-588a13f42c38.png)
)

**Comment by Asu4ni** [comment]
It seems weird that the assembly version of `FPSCamera` was `1.0.0.0` in the log rather than `2.1.0.*`. I suppose that the game on your side for some reasons requested or contained an older version (might be the original mod). One clue is that it was looking for `FPSCamera.VehicleCamera` which no longer exists and is replaced by `FPSCamera.Cam.VehicleCam`.

Please try disabling other possibly incompatible mods and see if the error disappears because I highly suspect that some other mods put the old assembly of `FPSCamera` in their folder. You could also check whether there are multiple `FPSCamera.dll`s in either the steam mod folder (`...\SteamLibrary\steamapps\workshop\content\*`) or the game's local mod folder (`...\<UserFolder>\AppData\Local\Colossal Order\Cities_Skylines\Addons\Mods`).
